version: '3'

services:
  laravel:
    build:
      context: ./
      dockerfile: .docker/dockerfiles/laravel/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: ./.docker/.env
    restart: unless-stopped
    volumes:
      - ./application:/var/www/htdocs/:delegated
      - ./.docker/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:ro
    working_dir: /var/www/htdocs
    depends_on:
      - db
      - mailpit

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "35080:80"
    volumes:
      - ./application:/var/www/htdocs/:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - "35081:3306"
    volumes:
      - ./.docker/.mysql:/var/lib/mysql:delegated

  db-testing: # PHPUnit testing database
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laraveltesting
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - "35083:3306"

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "35082:8025" # web ui

  composer:
    image: composer:2
    profiles:
      - composer
    restart: "no"
    volumes:
      - ./application:/app/:delegated
      - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
    command:
      composer install

  vite:
    image: node:20-alpine
    working_dir: /usr/src/app
    profiles:
      - vite
    restart: "no"
    ports:
      - "35174:35174"
    volumes:
      - ./application:/usr/src/app/:delegated
    command:
      npm run dev

  npm:
    image: node:20-alpine
    working_dir: /usr/src/app
    profiles:
      - npm
    restart: "no"
    volumes:
      - ./application:/usr/src/app/:delegated
    command:
      npm install
