# Sets the correct user for WSL2 environments.

version: '3'

services:
  laravel:
    user: "1000:1000"
    build:
      args:
        - WITHOUT_CRON=true
  npm:
    user: "1000:1000"
  vite:
    user: "1000:1000"
