version: '3'

services:
  # Core application services
  laravel:
    build:
      context: ./
      dockerfile: .docker/dockerfiles/laravel/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: ./.docker/.env
    restart: unless-stopped
    volumes:
      - ./application:/var/www/htdocs/
      - ./.docker/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./.docker/.laravel:/root
    working_dir: /var/www/htdocs
    depends_on:
      - db
      - mailpit

  web:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:35080:80"
    volumes:
      - ./application:/var/www/htdocs/
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - "127.0.0.1:35081:3306"
    volumes:
      - ./.docker/.mysql:/var/lib/mysql

  # Application testing
  selenium:
    image: 'selenium/standalone-chrome'
    profiles:
      - test
    platform: 'linux/amd64'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
        - '/dev/shm:/dev/shm'

  db-testing:
    image: mysql:8.0
    profiles:
      - test
    environment:
      - MYSQL_DATABASE=laraveltesting
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - "127.0.0.1:35083:3306"

  # Developer tools
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:35082:8025" # web ui

  composer:
    image: composer:2
    profiles:
      - composer
    restart: "no"
    volumes:
      - ./application:/app/
      - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
    command:
      composer install

  vite:
    image: node:20-alpine
    working_dir: /usr/src/app
    profiles:
      - vite
    restart: "no"
    ports:
      - "35174:35174"
    volumes:
      - ./application:/usr/src/app/
    command:
      npm run dev

  npm:
    image: node:20-alpine
    working_dir: /usr/src/app
    profiles:
      - npm
    restart: "no"
    volumes:
      - ./application:/usr/src/app/
    command:
      npm install
